#!/usr/bin/env python
"""
Transcribe Douyin creator videos from the enhanced CSV generated by
scrape-dy-creator-cdp.js.

Usage:
  python transcribe-dy-videos.py data/dy_xxx_with_video_xxx.csv --limit 3
  python transcribe-dy-videos.py data/dy_xxx_with_video_xxx.csv --model small

The script only keeps transcripts by default. Audio files are temporary unless
--keep-audio is passed.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MODEL_CACHE_DIR = ROOT / "models" / "huggingface"
os.environ.setdefault("HF_HOME", str(MODEL_CACHE_DIR))
os.environ.setdefault("HUGGINGFACE_HUB_CACHE", str(MODEL_CACHE_DIR / "hub"))
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

from faster_whisper import WhisperModel


DATA_DIR = ROOT / "data"
FFMPEG = ROOT / "node_modules" / "ffmpeg-static" / "ffmpeg.exe"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


def log(text: str) -> None:
    print(text.encode("utf-8", errors="replace").decode("utf-8", errors="replace"), flush=True)


def safe_name(text: str) -> str:
    text = re.sub(r'[\\/:*?"<>|]+', "-", text).strip()
    return text[:80] or "video"


def ascii_stem(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text).strip("._")
    text = re.sub(r"_+", "_", text).strip("._")
    return text[:120] or "douyin"


def download_temp_video(video_url: str, video_path: Path) -> None:
    request = urllib.request.Request(
        video_url,
        headers={
            "Referer": "https://www.douyin.com/",
            "User-Agent": USER_AGENT,
        },
    )
    with urllib.request.urlopen(request, timeout=120) as resp:
        with video_path.open("wb") as f:
            while True:
                chunk = resp.read(1024 * 1024)
                if not chunk:
                    break
                f.write(chunk)


def extract_audio(video_path: Path, wav_path: Path, max_seconds: int = 0) -> None:
    cmd = [
        str(FFMPEG),
        "-hide_banner",
        "-loglevel",
        "error",
    ]
    if max_seconds > 0:
        cmd.extend(["-t", str(max_seconds)])
    cmd.extend([
        "-i",
        str(video_path),
        "-vn",
        "-ac",
        "1",
        "-ar",
        "16000",
        "-y",
        str(wav_path),
    ])
    subprocess.run(cmd, check=True, timeout=180)


def transcribe_audio(model: WhisperModel, wav_path: Path) -> tuple[str, list[dict]]:
    segments_iter, info = model.transcribe(
        str(wav_path),
        language="zh",
        vad_filter=True,
        beam_size=5,
    )
    segments = [
        {"start": round(seg.start, 2), "end": round(seg.end, 2), "text": seg.text.strip()}
        for seg in segments_iter
    ]
    text = "".join(seg["text"] for seg in segments)
    return text, segments


def read_rows(csv_path: Path) -> list[dict]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def merge_existing_transcripts(rows: list[dict], source_csv: Path, output_dir: Path | None = None) -> dict[str, list[dict]]:
    out_dir = output_dir or (DATA_DIR / "transcripts")
    existing_csv = out_dir / f"{ascii_stem(source_csv.stem)}_transcripts.csv"
    existing_json = out_dir / f"{ascii_stem(source_csv.stem)}_segments.json"
    candidates = []
    if existing_csv.exists():
        candidates.append(existing_csv)
    if out_dir.exists():
        candidates.extend(p for p in out_dir.glob("*_transcripts.csv") if p != existing_csv)

    by_id: dict[str, dict] = {}
    for csv_file in candidates:
        try:
            for old in read_rows(csv_file):
                if old.get("id") and old.get("transcript_status") == "ok" and old.get("transcript"):
                    by_id[old["id"]] = old
        except Exception:
            continue

    for row in rows:
        old = by_id.get(row.get("id", ""))
        if old:
            row["transcript"] = old.get("transcript", "")
            row["transcript_status"] = old.get("transcript_status", "")
            row["transcript_error"] = old.get("transcript_error", "")

    segment_map: dict[str, list[dict]] = {}
    json_candidates = []
    if existing_json.exists():
        json_candidates.append(existing_json)
    if out_dir.exists():
        json_candidates.extend(p for p in out_dir.glob("*_segments.json") if p != existing_json)
    for json_file in json_candidates:
        try:
            with json_file.open("r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                segment_map.update(data)
        except Exception:
            continue
    return segment_map


def write_outputs(source_csv: Path, rows: list[dict], segment_map: dict[str, list[dict]], output_dir: Path | None = None) -> tuple[Path, Path]:
    out_dir = output_dir or (DATA_DIR / "transcripts")
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = ascii_stem(source_csv.stem)
    csv_out = out_dir / f"{stem}_transcripts.csv"
    json_out = out_dir / f"{stem}_segments.json"
    tmp_csv_out = out_dir / f".{stem}_transcripts.tmp.csv"
    tmp_json_out = out_dir / f".{stem}_segments.tmp.json"

    fieldnames = list(rows[0].keys()) if rows else []
    for field in ["transcript", "transcript_status", "transcript_error"]:
      if field not in fieldnames:
          fieldnames.append(field)

    with tmp_csv_out.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    tmp_csv_out.replace(csv_out)

    with tmp_json_out.open("w", encoding="utf-8") as f:
        json.dump(segment_map, f, ensure_ascii=False, indent=2)
    tmp_json_out.replace(json_out)

    return csv_out, json_out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("csv_path", type=Path)
    parser.add_argument("--limit", type=int, default=0, help="Only transcribe first N rows")
    parser.add_argument("--model", default="base", help="Whisper model: tiny, base, small, medium, large-v3")
    parser.add_argument("--device", default="cpu", help="cpu or cuda")
    parser.add_argument("--compute-type", default="int8", help="int8, int8_float16, float16, float32")
    parser.add_argument("--keep-audio", action="store_true")
    parser.add_argument("--max-seconds", type=int, default=0, help="Only transcribe first N seconds of each video")
    parser.add_argument("--output-dir", type=Path, default=None, help="Directory for transcript CSV/JSON")
    args = parser.parse_args()

    if not FFMPEG.exists():
        raise SystemExit(f"ffmpeg not found: {FFMPEG}")

    rows = read_rows(args.csv_path)
    segment_map: dict[str, list[dict]] = merge_existing_transcripts(rows, args.csv_path, args.output_dir)
    target_rows = rows[: args.limit] if args.limit else rows
    audio_dir = DATA_DIR / "audio_tmp"
    if args.keep_audio:
        audio_dir.mkdir(parents=True, exist_ok=True)

    log(f"Loading Whisper model: {args.model} ({args.device}, {args.compute_type})")
    model = WhisperModel(args.model, device=args.device, compute_type=args.compute_type)

    for idx, row in enumerate(target_rows, start=1):
        video_url = row.get("video_url", "")
        video_id = row.get("id", f"row_{idx}")
        title = row.get("desc", "")[:42]
        log(f"[{idx}/{len(target_rows)}] {video_id} {title}")

        if row.get("transcript_status") == "ok" and row.get("transcript"):
            log("  skip, existing transcript")
            continue

        if not video_url:
            row["transcript_status"] = "missing_video_url"
            row["transcript_error"] = "video_url is empty"
            row["transcript"] = ""
            continue

        temp_dir = Path(tempfile.gettempdir())
        wav_path = (audio_dir / f"{video_id}.wav") if args.keep_audio else temp_dir / f"dy_{video_id}.wav"
        video_path = temp_dir / f"dy_{video_id}.mp4"
        try:
            download_temp_video(video_url, video_path)
            extract_audio(video_path, wav_path, args.max_seconds)
            transcript, segments = transcribe_audio(model, wav_path)
            row["transcript"] = transcript
            row["transcript_status"] = "ok"
            row["transcript_error"] = ""
            segment_map[video_id] = segments
            log(f"  ok, {len(transcript)} chars")
        except Exception as exc:
            row["transcript"] = ""
            row["transcript_status"] = "error"
            row["transcript_error"] = str(exc)
            log(f"  error: {exc}")
        finally:
            try:
                video_path.unlink()
            except FileNotFoundError:
                pass
            if not args.keep_audio:
                try:
                    wav_path.unlink()
                except FileNotFoundError:
                    pass
        csv_out, json_out = write_outputs(args.csv_path, rows, segment_map, args.output_dir)
        log(f"  checkpoint: {csv_out}")

    csv_out, json_out = write_outputs(args.csv_path, rows, segment_map, args.output_dir)
    log(f"CSV: {csv_out}")
    log(f"JSON: {json_out}")


if __name__ == "__main__":
    main()
